# .github/workflows/android-ci.yml
name: Android CI (Build Debug APK)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: EcoSphere   # 👈 run Gradle from the project folder
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.9'

      - name: Build Debug APK
        run: gradle :app:assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: EcoSphere-debug-apk
          path: EcoSphere/app/build/outputs/apk/debug/app-debug.apk  # 👈 matches the working dir
